def preprocessing_description(text):
    text = str(text)
    for _ in range(100):
        text = text.replace('\n', ' ')
    for _ in range(10):
        text = text.replace('&', ' and ')
        text = text.replace('·', ' ')
        text = text.replace('/', ' ')
        text = text.replace('(', ' ')
        text = text.replace(')', ' ')
        text = text.replace('[', ' ')
        text = text.replace(']', ' ')
        text = text.replace(':', ' ')
        text = text.replace('.', ' ')
        text = text.replace('-', ' ')
        text = text.replace('#', ' ')
        text = text.replace("'", ' ')
        text = text.replace('"', ' ')
        text = text.replace('`', ' ')
        text = text.replace('|', ' ')
        text = text.replace(';', ' ')
        text = text.replace('<', ' ')
        text = text.replace('>', ' ')
        text = text.replace('?', ' ')
        text = text.replace('~', ' ')
        text = text.replace('!', ' ')
        text = text.replace('$', ' ')
        text = text.replace('%', ' ')
        text = text.replace('^', ' ')
        text = text.replace('*', ' ')
        text = text.replace('_', ' ')
        text = text.replace('+', ' ')
        text = text.replace('=', ' ')
        text = text.replace('{', ' ')
        text = text.replace('}', ' ')
        text = text.replace('–', ' ')
        text = text.replace('’', ' ')
        text = text.replace(',', '')
    for _ in range(10):
        text = text.replace("  ", ' ')
    for _ in range(3):
        text = text.replace(r'\uf0b7', ' ')
        text = text.replace('\uf0b7', ' ')
        text = text.replace('Job Summary ', ' ')
        text = text.replace('Job Description ', ' ')
        text = text.replace('\\', ' ')
    text = text.lstrip().rstrip()
    return text

def preprocessing_title_location_company(text):
    text = str(text)
    for _ in range(10):
        text = text.replace('&', 'and')
        text = text.replace("'", ' ')
        text = text.replace('"', ' ')
        text = text.replace('(', ' ')
        text = text.replace(')', ' ')
        text = text.replace('[', ' ')
        text = text.replace(']', ' ')
        text = text.replace('{', ' ')
        text = text.replace('}', ' ')
        text = text.replace('-', ' ')
        text = text.replace('#', ' ')
        text = text.replace('/', ' ')
        text = text.replace('!', ' ')
        text = text.replace('$', ' ')
        text = text.replace('%', ' ')
        text = text.replace('^', ' ')
        text = text.replace('*', ' ')
        text = text.replace('_', ' ')
        text = text.replace('+', ' ')
        text = text.replace('=', ' ')
        text = text.replace('<', ' ')
        text = text.replace('>', ' ')
        text = text.replace('?', ' ')
        text = text.replace('~', ' ')
        text = text.replace('`', ' ')
        text = text.replace('|', ' ')
        text = text.replace(';', ' ')
        text = text.replace('.', ' ')
        text = text.replace(',', ' ')
        text = text.replace(':', ' ')
        text = text.replace('\\', ' ')
        
    for _ in range(10):
        text = text.replace("  ", ' ')
    text = text.lstrip().rstrip()
    return text

def preprocessing_salary(text):
    text = str(text)
    for _ in range(20):
        text = text.replace('&', 'and')
        text = text.replace(',', '')
        text = text.replace('/', ' ')
        text = text.replace("'", ' ')
        text = text.replace('"', ' ')
        text = text.replace(':', ' ')
        text = text.replace('–', ' ')
        text = text.replace('.', ' ')
        text = text.replace('|', ' ')
        text = text.replace(';', ' ')
        text = text.replace('’', ' ')
        text = text.replace('?', ' ')
        text = text.replace('~', ' ')
        text = text.replace('!', ' ')
        text = text.replace('$', ' ')
        text = text.replace('%', ' ')
        text = text.replace('^', ' ')
        text = text.replace('*', ' ')
        text = text.replace('_', ' ')
        text = text.replace('+', ' ')
        text = text.replace('=', ' ')
        text = text.replace('`', ' ')
        text = text.replace('\\', ' ')
        text = text.replace('(', ' ')
        text = text.replace(')', ' ')
        text = text.replace('<', ' ')
        text = text.replace('>', ' ')
        text = text.replace('[', ' ')
        text = text.replace(']', ' ')
        text = text.replace('{', ' ')
        text = text.replace('}', ' ')
        
    for _ in range(5):
        text = text.replace('₹', '')
        text = text.replace('-', '')
        text = text.replace(' a ', ' ')
        text = text.replace(' an ', ' ')
    
    for _ in range(10):
        text = text.replace('  ', ' ')
    text = text.lstrip().rstrip().lower()
    return text

def salary_remove_unit(text):
    text = str(text)
    text = text.replace(' month', '')
    text = text.replace(' year', '')
    text = text.replace(' week', '')
    text = text.replace(' day', '')
    text = text.replace(' hour', '')
    text = text.lstrip().rstrip()
    return text